# Generated by Django 4.1.2 on 2023-02-09 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imageService.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('public', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.ImageField(unique=True, upload_to=imageService.models.upload_to)),
                ('query', models.CharField(default='default', max_length=50)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageService.file')),
            ],
        ),
    ]
